const CANVAS_WIDTH = 650;
const CANVAS_HEIGHT = 900;
const LEFT_ARROW = 37;
const RIGHT_ARROW = 39;
const UP_ARROW = 38;
const DOWN_ARROW = 40;
const SPACE_BAR = 32;
const scoreHolder = document.querySelector("h1 span");
//let scoreCounter = "Score: ";